my_postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '*Postgres123#'
      port: 5432
      dbname: medical_warehouse
      schema: analytics
      threads: 4